version: '3.8'

services:
  helidon:
    build:
      context: .
      dockerfile: ./helidon/Dockerfile
    ports:
      - "48080:10080"
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    volumes:
      - ./mysql/data/:/var/lib/mysql
    env_file:
      - ./mysql-variables.env
    ports:
      - "43306:3306"

  vue:
    build:
      context: .
      dockerfile: ./vue/Dockerfile
    ports:
      - "43000:3000"
